### ISSUE TITLE
Align Smack's keystore with Openfire

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/Openfire-Meetings#38]
#37 pulled in a version of Jitsi components that now use Smack 4, instead of Smack 3. One of the improvements in Smack 4 is that it better adheres to TLS settings.

Sadly, this results in problems when trying to set-up a OFMeet-based meet on a domain that doesn't have any properly signed* certificates for your domain (a workaround is to disable C2S encryption in Openfire, but you really don't want to do that in production)

We should make Smack (that's in Jitsi) use the Openfire keystores. That way, what's in Openfire, should be trusted by Smack - including things like self-signed certificates.

\* your mileage may vary.

**Comment by deleolajide** [comment]
I think the TLS connection for the focus user with certificate checking can be simplified. I am currently reworking the Openfire XMPPConnection class I used with smack 3.x. It is based on the work I did to port the chatapi plugin from smack 3.x to 4.x. 

With this option, we could  also make Jitsi configurable to use an extended trusted Openfire Connection class to connect instead of the standard TCP Connection class.

**Comment by deleolajide** [comment]
If we can add the OpenfireConnection class to smack 4.x with PR, it might make it easier for the Jitsi team to use it and make the connection type configurable

**Comment by deleolajide** [comment]
Here is my first attempt at the smack xmpp connection class based using Openfire VirtualConnection instead of a TCP connection. It fixes the TLS issue for me at the moment.

https://github.com/Traderlynk/ofmeet-openfire-plugin/blob/master/offocus/src/java/org/jivesoftware/smack/tcp/XMPPTCPConnection.java

**Comment by guusdk** [comment]
Instead of modifying the client-sided keystores, I've worked with the people of Jitsi to add a setting that allows us to skip the strict certificate checking that causes this issue: https://github.com/jitsi/jicofo/pull/261. As we're connecting with Smack to Openfire from within the JVM (on the same server), there's not much added value in certificate checks.
